project:
  type: website
  output-dir: docs

website:
  title: "Tim Huegerich â€“ economics and other pedantry"
  description: "Homepage of Tim Huegerich"
  navbar:
    right:
      - href: https://hugetim.github.io/nbstata/
        text: nbstata
      - href: blog.qmd
        text: blog
    background: light
  back-to-top-navigation: true
  site-url: https://hugetim.github.io
  repo-url: https://github.com/hugetim/hugetim.github.io
  repo-actions: source
  twitter-card: true
  
format:
  html:
    theme:
      - cosmo
      - brand
    fontsize: 15px
